### panic
panic会终止程序并报出出错位置和出错信息.

遇到panic时,默认会展开并清空堆栈.当设置项目profile为abort时,二进制文件体积会变小.

```
# cargo.toml
[profile.release]
panic = 'abort'
```
#### backtrace
backtrace 是一个执行到目前位置所有被调用的函数的列表。

当出现panic不在项目源代码,而是在其他三方文件中,可以查看backtrace[RUST_BACKTRACE=1  cargo run].backtrace查看需要开启debug标识.当没有指定release模式时,默认是开启debug的.



#### 匹配不同类型错误的例子
```
use std::fs::File;
use std::io::ErrorKind;
 
fn main() {
    let f = File::open("text.txt");
    // 需要注意,当这里声明一个let file = 去接match返回值时,不会报错;
    // 但是如果没有声明f,确在Ok(file)里返回了file,就会报错:  希望返回()但返回了file
    // 因为这里会作为main的返回值,而main只能返回() 或者 Result类型
    let file = match f {
        Ok(file) => file,
        Err(err) => {
            println!("err, {}", err);
            match err.kind() {
                ErrorKind::NotFound => match File::create("text.txt") {
                    Ok(file) => file,
                    Err(err) => panic!("Problem creating the file: {:?}", err),
                },
                other => panic!("Problem opening the file: {:?}", other),
            }
        }
    };
}
 
// 学习完13章闭包后会有更好的写法,不用写很多match
use std::fs::File;
use std::io::ErrorKind;
 
fn main() {
    let f = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```
### 强大的unwrap  & expect
帮助我们在Err时进行panic

帮我们简写了match xxx {Ok(xx) => {}, Err(err) => { panic!(err)}}

1. unwrap
```
use std::fs::File;
 
fn main() {
    let f = File::open("hello.txt").unwrap();
}
```
2. expect

可以自定义panic时的错误信息

```
use std::fs::File;
 
fn main() {
    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
```
##### 强大的?
帮助我们在Err时将错误返回,而不panic—传播错误
```

use std::io;
use std::io::Read;
use std::fs::File;
 
fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");
 
    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };
 
    let mut s = String::new();
 
    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```
直接替换为:

```
use std::io;
use std::io::Read;
use std::fs::File;
 
fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s) // 由于只有Err会被返回,当Ok时就需要我们手动处理返回了
}
```
问号还支持链式调用:
```

use std::io;
use std::io::Read;
use std::fs::File;
 
fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();
 
    File::open("hello.txt")?.read_to_string(&mut s)?;
 
    Ok(s)
}
```
**使用?表达式有什么不同?**

> match 表达式与问号运算符所做的有一点不同：? 运算符所使用的错误值被传递给了 from 函数，它定义于标准库的 From trait 中，其用来将错误从一种类型转换为另一种类型。当 ? 运算符调用 from 函数时，收到的错误类型被转换为由当前函数返回类型所指定的错误类型。这在当函数返回单个错误类型来代表所有可能失败的方式时很有用，即使其可能会因很多种原因失败。只要每一个错误类型都实现了 from 函数来定义如何将自身转换为返回的错误类型，? 运算符会自动处理这些转换。

即:  ?是进行了一个from函数的转换,用于统一将不同错误类型(只要他实现了from trait)转换为该函数声明的类型.

上述打开文件并读取,实际上有一个更简单的方法
```

use std::io;
use std::fs;
 
fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

?只能用于这样的函数中:只能在返回 Result 或者其它实现了 std::ops::Try 的类型的函数[??遗留问题]使用 ? 运算符

[错误指出只能在返回 Result 或者其它实现了 std::ops::Try 的类型的函数中使用 ? 运算符。当你期望在不返回 Result 的函数中调用其他返回 Result 的函数时使用 ? 的话，有两种方法修复这个问题。一种技巧是将函数返回值类型修改为 Result<T, E>，如果没有其它限制阻止你这么做的话。另一种技巧是通过合适的方法使用 match 或 Result 的方法之一来处理 Result<T, E>] - 如何处理???
```

// 如何处理这个错误?, 能让返回值是()
use std::fs::File;
 
fn main() {
    let f = File::open("hello.txt")?;
}
```
main函数比较特殊,只能返回()或Result<T,E>
```

use std::error::Error;
use std::fs::File;
// Box<dyn Error> 被称为 “trait 对象”
// 目前可以理解 Box<dyn Error> 为使用 ? 时 main 允许返回的 “任何类型的错误”
fn main() -> Result<(), Box<dyn Error>> {
    let f = File::open("hello.txt")?;
 
    Ok(())
}
```
### 泛型
函数泛型/结构体/枚举泛型

方法泛型
```

struct Point<T> {
    x: T,
    y: T
}
 
impl<T> Point<T> {
    fn x(&self) -> &T {
        &self.x
    }
}
 
fn main() {
    let p = Point {
        x: 1,
        y: 4
    };
    println!("{}", p.x());
}
```
也可以为特定类型声明impl:
```

impl Point<f32> {
    fn distance_from_origin(&self) -> f32 {
        (self.x.powi(2) + self.y.powi(2)).sqrt()
    }
}
```

**注:**
泛型速度不会变慢;在编译时会进行泛型代码的[单态化],编译器寻找所有泛型代码被调用的位置并使用泛型代码针对具体类型生成代码。

###### Trait
类似于其他语言的interface.是一些行为(方法-有self参数)的集合. [类似ts中的extends]

trait的声明

```
pub trait Summary {
    fn summarize(&self) -> String {}; // 分号结尾,表明声明而非定义
}```
为类型实现trait
```

struct Point{
    x: i32,
    y: i32
}
 
impl Suumary for Point {
    fn summarize(&self) -> String {
        String::from("summarize")
    }
}```
**注:** 相干性|孤儿原则

实现trait的前提–trait或者要实现trait的类型在本地作用域.(即不可以为外部类型实现外部trait)

trait的默认行为

在声明时,实现一个默认方法
```

pub trait Summary {
    fn summarize(&self) -> String {
        String::from("(Read more...)")
    }
}
 
// 使用
impl Summary for Point {} // 空结构
```
在trait中,一个方法默认调用另一个方法

目的?

请注意，无法从相同方法的重载实现中调用默认方法。
```

pub trait Summary {
    fn summarize_author(&self) -> String;
 
    fn summarize(&self) -> String {
        format!("(Read more from {}...)", self.summarize_author())
    }
}
 
impl Summary for Tweet {
    fn summarize_author(&self) -> String {
        format!("@{}", self.username)
    }
}```
trait做参数
```

pub fn notify(item: impl Summary) {
    println!("Breaking news! {}", item.summarize());
}
```
是一种泛型的语法糖

```
pub fn notify<T: Summary>(item: T) {
    println!("Breaking news! {}", item.summarize());
}
```
当参数超过一个时,对多个参数类型的相同性约束,只能通过泛型约束(即称为:trait bound),trait做不到:

```rs
pub fn notify(item1: impl Summary, item2: impl Summary) {}
pub fn notify<T: Summary>(item1: T, item2: T) {}

```
多个trait约束:
```

pub fn notify(item: impl Summary + Display) {}
pub fn notify<T: Summary + Display>(item: T) {}```
### 生命周期
#### 函数生命周期
它的实际含义是 longest 函数返回的引用的生命周期与传入该函数的引用的生命周期的较小者一致。

```rs
fn longest<'a>(x: &'a str, y: &'a str) -> &'a str {
    if x.len() > y.len() {
        x
    } else {
        y
    }
}
```
生命周期不改变变量本身的生命周期,只是告诉借用检查器如何检测未知生命周期的内容

函数参数和返回中,需要泛型生命周期的变量与函数实现/借用返回有关
```rs
fn longest<'a>(x: &'a str, y: &str/*y不需要生命周期*/) -> &'a str {
    x
}
```
函数或方法的参数的生命周期被称为 输入生命周期（input lifetimes），而返回值的生命周期被称为 输出生命周期（output lifetimes）。

#### 结构体生命周期
```rs
struct ImportantExcerpt<'a> {
    part: &'a str,
}
 
fn main() {
    let novel = String::from("Call me Ishmael. Some years ago...");
    let first_sentence = novel.split('.')
        .next()
        .expect("Could not find a '.'");
    let i = ImportantExcerpt { part: first_sentence };
}
```
上例中,结构体本身的使用范围不可以超过其中的引用生命周期,如下就是错误的
```rs
#[derive(Debug)]
struct ImportantExcerpt<'a> {
    part: &'a str,
}
 
fn main() {
    let i;
    {
        let novel = String::from("Call me Ishmael. Some years ago...");
        let first_sentence = novel.split('.')
        .next()
        .expect("Could not find a '.'");
        i = ImportantExcerpt { part: first_sentence };
 
    }
    println!("{:?}", i);
     
}
```
##### 省略生命周期
规则

编译器采用三条规则来判断引用何时不需要明确的标注。第一条规则适用于输入生命周期，后两条规则适用于输出生命周期。如果编译器检查完这三条规则后仍然存在没有计算出生命周期的引用，编译器将会停止并生成错误。这些规则适用于 fn 定义，以及 impl 块。

第一条规则是每一个是引用的参数都有它自己的生命周期参数。换句话说就是，有一个引用参数的函数有一个生命周期参数：fn foo<'a>(x: &'a i32)，有两个引用参数的函数有两个不同的生命周期参数，fn foo<'a, 'b>(x: &'a i32, y: &'b i32)，依此类推。

第二条规则是如果只有一个输入生命周期参数，那么它被赋予所有输出生命周期参数：fn foo<'a>(x: &'a i32) -> &'a i32。

第三条规则是如果方法有多个输入生命周期参数并且其中一个参数是 &self 或 &mut self，说明是个对象的方法(method)(译者注： 这里涉及 Rust 的面向对象，参见第 17 章), 那么所有输出生命周期参数被赋予 self 的生命周期。第三条规则使得方法更容易读写，因为只需更少的符号。


```rs
fn longest(x: &str, y: &str) -> &str {}
// 根据1. fn longest<'a, 'b>(x: &'a str, y: &'b str) -> &str {}
// 2.3不适用,因此返回类型生命周期无法推测出导致最开始的报错
```
综合示例
```rs
use std::fmt::Display;
 
fn longest_with_an_announcement<'a, T>(x: &'a str, y: &'a str, ann: T) -> &'a str
    where T: Display
{
    println!("Announcement! {}", ann);
    if x.len() > y.len() {
        x
    } else {
        y
    }
}
```
